import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='flex'>
          <div className='bg-white text-black w-1/4 h-screen'>
            <ul className='space-y-4 p-4'>
              <li>
                <Link href='/'>Home</Link>
              </li>
              <li>
                <Link href='/content'>Content</Link>
              </li>
              <li>
                <Link href='/api/greet/test-user'>
                  <code className='font-mono font-bold'>API</code>
                </Link>
              </li>
            </ul>
          </div>
          <div className='w-4/5 h-screen p-8'>{children}</div>
        </main>
      </body>
    </html>
  );
}
